"""
Seed script — populates MongoDB with 40+ products spanning all intent categories.
Run with: python seed_products.py

Product embeddings are auto-generated by the FastAPI server on POST /products.
"""
import requests
import sys

BASE_URL = "http://localhost:8000"

PRODUCTS = [
    # ── Health / Cold / Immunity ────────────────────────────────────────────
    {
        "name": "Organic Raw Honey",
        "description": "Pure organic honey with antibacterial properties. Natural remedy for cough, cold, and sore throat. Rich in antioxidants and helps boost immunity.",
        "price": 8.99, "category": "Health", "unit": "500g jar",
        "image_url": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800",
        "tags": ["honey", "immunity", "cold remedy", "cough", "sore throat", "natural", "antibacterial"],
        "stock": 80, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Ginger Root Powder",
        "description": "100% pure dried ginger powder. Excellent for cold, nausea, and anti-inflammation. Makes ginger tea to soothe sore throat and relieve congestion.",
        "price": 3.49, "category": "Health", "unit": "200g",
        "image_url": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
        "tags": ["ginger", "cold", "immunity", "anti-inflammatory", "nausea", "sore throat"],
        "stock": 100, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Ginger Honey Lemon Tea",
        "description": "Premium ginger tea with honey and lemon. Soothes cough, cold, sore throat, and congestion. Boosts immunity and warms you up instantly.",
        "price": 5.99, "category": "Beverages", "unit": "20 tea bags",
        "image_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800",
        "tags": ["ginger tea", "honey", "lemon", "cold", "cough", "immunity", "sore throat", "herbal", "warm"],
        "stock": 150, "lat": 28.6142, "lng": 77.2095,
    },
    {
        "name": "Dabur Tulsi Drops",
        "description": "Concentrated Tulsi (Holy Basil) extract drops. Ancient Ayurvedic remedy for respiratory infections, cold, cough, and immunity boosting.",
        "price": 6.49, "category": "Health", "unit": "30ml bottle",
        "image_url": "https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=800",
        "tags": ["tulsi", "holy basil", "immunity", "cold", "cough", "ayurvedic", "respiratory"],
        "stock": 60, "lat": 28.6138, "lng": 77.2088,
    },
    {
        "name": "Turmeric Golden Milk Powder",
        "description": "Organic turmeric powder with black pepper for maximum curcumin absorption. Anti-inflammatory, boosts immunity, and fights cold and flu symptoms.",
        "price": 4.99, "category": "Health", "unit": "250g",
        "image_url": "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800",
        "tags": ["turmeric", "golden milk", "anti-inflammatory", "immunity", "cold", "curcumin", "haldi"],
        "stock": 90, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Vitamin C Effervescent Tablets",
        "description": "1000mg Vitamin C fizzy tablets. Strengthens immune system, fights cold and flu, provides antioxidant protection. Lemon flavour.",
        "price": 7.99, "category": "Health", "unit": "20 tablets",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["vitamin c", "immunity", "cold", "flu", "antioxidant", "supplement"],
        "stock": 120, "lat": 28.6141, "lng": 77.2093,
    },
    {
        "name": "Vicks Cough Syrup",
        "description": "Trusted cough syrup for dry and wet cough relief. Contains honey and ginger extracts. Soothes irritated throat and helps clear chest congestion.",
        "price": 5.49, "category": "Medicine", "unit": "100ml",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["cough syrup", "cough", "cold", "chest congestion", "sore throat", "medicine"],
        "stock": 70, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Strepsils Lozenges",
        "description": "Medicated throat lozenges for sore throat pain relief. Antiseptic formula kills bacteria causing throat infection. Honey-lemon flavour.",
        "price": 3.99, "category": "Medicine", "unit": "24 lozenges",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["sore throat", "throat lozenge", "cold", "cough", "antiseptic", "honey lemon"],
        "stock": 100, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Amla Indian Gooseberry Juice",
        "description": "Fresh-pressed Amla juice, highest natural source of Vitamin C. Boosts immunity, fights cold and cough, improves digestion and skin health.",
        "price": 4.99, "category": "Beverages", "unit": "500ml",
        "image_url": "https://images.unsplash.com/photo-1622683083025-bfd56a33af2d?w=800",
        "tags": ["amla", "vitamin c", "immunity", "cold", "ayurvedic", "gooseberry"],
        "stock": 50, "lat": 28.6140, "lng": 77.2092,
    },

    # ── Fever / Pain ────────────────────────────────────────────────────────
    {
        "name": "Paracetamol 500mg",
        "description": "Fast-acting paracetamol tablets for fever, headache, body pain, and cold symptoms. Gentle on stomach. Pack of 10 tablets.",
        "price": 2.49, "category": "Medicine", "unit": "10 tablets",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["paracetamol", "fever", "headache", "pain relief", "cold", "medicine"],
        "stock": 200, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Electrolyte ORS Powder",
        "description": "Oral rehydration salts to replenish electrolytes lost during fever, vomiting, diarrhea, or intense workout. Lemon-orange flavour.",
        "price": 3.99, "category": "Health", "unit": "10 sachets",
        "image_url": "https://images.unsplash.com/photo-1625708458528-802ec79b1ed8?w=800",
        "tags": ["electrolyte", "ors", "rehydration", "fever", "dehydration", "thirst", "sports"],
        "stock": 120, "lat": 28.6141, "lng": 77.2093,
    },
    {
        "name": "Coconut Water",
        "description": "100% natural tender coconut water. Rich in electrolytes, potassium, and minerals. Perfect for rehydration after fever, exercise, or heat.",
        "price": 2.99, "category": "Beverages", "unit": "330ml can",
        "image_url": "https://images.unsplash.com/photo-1559181567-c3190ca9be46?w=800",
        "tags": ["coconut water", "electrolyte", "hydration", "dehydrated", "thirsty", "fever", "natural"],
        "stock": 150, "lat": 28.6140, "lng": 77.2091,
    },

    # ── Energy / Gym / Weakness ─────────────────────────────────────────────
    {
        "name": "Whey Protein Chocolate",
        "description": "25g protein per scoop. Complete amino acid profile for muscle building, post-workout recovery, and combating weakness. Rich chocolate flavour.",
        "price": 29.99, "category": "Fitness", "unit": "1kg tub",
        "image_url": "https://images.unsplash.com/photo-1579722820308-d74e571900a9?w=800",
        "tags": ["whey protein", "protein", "muscle", "gym", "workout", "weak", "energy", "bodybuilding"],
        "stock": 40, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Monster Energy Drink",
        "description": "Original Monster energy drink with caffeine, B-vitamins, and taurine. Instant energy boost for gym, work, or whenever you feel tired and sluggish.",
        "price": 3.49, "category": "Beverages", "unit": "500ml can",
        "image_url": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800",
        "tags": ["energy drink", "energy", "caffeine", "tired", "weak", "gym", "workout", "boost"],
        "stock": 200, "lat": 28.6142, "lng": 77.2095,
    },
    {
        "name": "Multivitamin Daily Capsules",
        "description": "Complete daily multivitamin with 25 essential vitamins and minerals. Combats fatigue, weakness, and nutrient deficiency. Supports energy metabolism.",
        "price": 12.99, "category": "Health", "unit": "60 capsules",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["multivitamin", "vitamin", "mineral", "tired", "weak", "fatigue", "energy", "supplement"],
        "stock": 80, "lat": 28.6138, "lng": 77.2088,
    },
    {
        "name": "Mixed Nuts and Almonds",
        "description": "Premium roasted mixed nuts: almonds, cashews, walnuts, pistachios. High in protein, healthy fats, and energy. Perfect gym snack for weakness.",
        "price": 9.99, "category": "Snacks", "unit": "500g",
        "image_url": "https://images.unsplash.com/photo-1590439471364-192aa70c0b53?w=800",
        "tags": ["almond", "nuts", "protein", "energy", "gym", "healthy snack", "weak", "keto"],
        "stock": 100, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Banana Bunch",
        "description": "Fresh ripe bananas, nature's original energy bar. High in potassium, complex carbs, and B6. Great pre-workout fuel and quick energy for fatigue.",
        "price": 1.99, "category": "Fruits", "unit": "bunch of 6",
        "image_url": "https://images.unsplash.com/photo-1571501478200-720616235bbf?w=800",
        "tags": ["banana", "energy", "fruit", "potassium", "gym", "workout", "tired"],
        "stock": 150, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Iron + B12 Supplement",
        "description": "Iron and Vitamin B12 supplement to combat anaemia, chronic fatigue, and weakness. Supports red blood cell production and energy levels.",
        "price": 11.99, "category": "Health", "unit": "30 tablets",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["iron", "b12", "vitamin", "fatigue", "weak", "tired", "anaemia", "energy"],
        "stock": 60, "lat": 28.6139, "lng": 77.2090,
    },

    # ── Diet / Weight Loss ──────────────────────────────────────────────────
    {
        "name": "Lipton Green Tea",
        "description": "Premium green tea with antioxidants and EGCG. Boosts metabolism and aids weight loss. Low calorie, refreshing, and helps burn fat naturally.",
        "price": 4.49, "category": "Beverages", "unit": "25 tea bags",
        "image_url": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800",
        "tags": ["green tea", "weight loss", "diet", "metabolism", "antioxidant", "slim", "fat burn"],
        "stock": 200, "lat": 28.6141, "lng": 77.2093,
    },
    {
        "name": "Rolled Oats",
        "description": "100% whole grain rolled oats. High fibre, low glycemic index. Keeps you full, supports weight loss, lowers cholesterol. Ideal diet breakfast.",
        "price": 3.99, "category": "Breakfast", "unit": "1kg",
        "image_url": "https://images.unsplash.com/photo-1584263347416-85a696b4eda7?w=800",
        "tags": ["oats", "weight loss", "diet", "fibre", "low calorie", "healthy", "slim", "breakfast"],
        "stock": 120, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Chia Seeds",
        "description": "Organic chia seeds packed with omega-3, fibre, and protein. Expands in stomach to reduce appetite. Great for weight loss and keto diet.",
        "price": 6.99, "category": "Health", "unit": "250g",
        "image_url": "https://images.unsplash.com/photo-1638436462997-cf78c98ba4ea?w=800",
        "tags": ["chia seeds", "weight loss", "diet", "omega-3", "keto", "protein", "fibre", "slim"],
        "stock": 80, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Quinoa Grain",
        "description": "Complete plant-based protein with all 9 essential amino acids. Gluten-free superfood for weight loss, muscle building, and clean diet.",
        "price": 8.49, "category": "Grains", "unit": "500g",
        "image_url": "https://images.unsplash.com/photo-1586201375761-83865001e31c?w=800",
        "tags": ["quinoa", "superfood", "diet", "weight loss", "protein", "gluten-free", "healthy", "slim"],
        "stock": 60, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Fresh Garden Salad Mix",
        "description": "Ready-to-eat mixed lettuce, spinach, rocket, and greens. Low calorie, high fibre. Perfect for diet meals, weight loss, and clean eating.",
        "price": 3.49, "category": "Vegetables", "unit": "200g bag",
        "image_url": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
        "tags": ["salad", "lettuce", "greens", "diet", "weight loss", "low calorie", "healthy", "slim"],
        "stock": 80, "lat": 28.6138, "lng": 77.2088,
    },
    {
        "name": "Apple Cider Vinegar",
        "description": "Raw unfiltered organic ACV with mother. Aids weight loss, improves digestion, controls blood sugar, and suppresses appetite when taken before meals.",
        "price": 7.49, "category": "Health", "unit": "500ml",
        "image_url": "https://images.unsplash.com/photo-1562611054-e70a1b6169a7?w=800",
        "tags": ["apple cider vinegar", "acv", "weight loss", "diet", "digestion", "slim", "metabolism"],
        "stock": 70, "lat": 28.6141, "lng": 77.2093,
    },
    {
        "name": "Protein Bar - Chocolate Peanut",
        "description": "20g protein, 5g sugar. Meal replacement bar for gym-goers and dieters. Fills you up without the calories. Ideal for weight loss and muscle gain.",
        "price": 2.99, "category": "Fitness", "unit": "1 bar (60g)",
        "image_url": "https://images.unsplash.com/photo-1594070319944-7c0cbebb6f58?w=800",
        "tags": ["protein bar", "protein", "diet", "weight loss", "gym", "snack", "low sugar"],
        "stock": 200, "lat": 28.6140, "lng": 77.2091,
    },

    # ── Keto ────────────────────────────────────────────────────────────────
    {
        "name": "Avocado (Hass)",
        "description": "Creamy premium Hass avocado loaded with healthy fats, fibre, and potassium. A staple for keto, LCHF, and heart-healthy diets.",
        "price": 3.99, "category": "Fruits", "unit": "piece",
        "image_url": "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=800",
        "tags": ["avocado", "keto", "healthy fat", "diet", "low carb", "lchf"],
        "stock": 50, "lat": 28.6145, "lng": 77.2100,
    },
    {
        "name": "Free Range Eggs",
        "description": "Farm-fresh free-range eggs. High quality protein, healthy fats, and nutrients. Keto friendly, gym staple, and perfect daily nutrition.",
        "price": 3.99, "category": "Dairy & Eggs", "unit": "12 eggs",
        "image_url": "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800",
        "tags": ["egg", "protein", "keto", "gym", "healthy fat", "breakfast", "low carb"],
        "stock": 100, "lat": 28.6139, "lng": 77.2090,
    },

    # ── Pasta / Cooking (for recipe queries) ────────────────────────────────
    {
        "name": "Barilla Spaghetti Pasta",
        "description": "Classic Italian durum wheat spaghetti. Cook in 8 minutes for the perfect pasta base. Great for pasta carbonara, bolognese, or arrabbiata.",
        "price": 2.49, "category": "Pantry", "unit": "500g",
        "image_url": "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0?w=800",
        "tags": ["pasta", "spaghetti", "italian", "cooking", "dinner", "carbs"],
        "stock": 200, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Tomato Pasta Sauce",
        "description": "Rich Italian-style tomato sauce with basil and garlic. Ready-to-use pasta sauce for quick weeknight dinners. No preservatives, fresh taste.",
        "price": 3.49, "category": "Pantry", "unit": "400g jar",
        "image_url": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800",
        "tags": ["pasta sauce", "tomato", "italian", "cooking", "pasta", "pizza"],
        "stock": 150, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Parmesan Cheese",
        "description": "Aged Italian Parmigiano Reggiano. Sharp, nutty flavour perfect for pasta, risotto, and salads. Adds authentic Italian taste to any dish.",
        "price": 6.99, "category": "Dairy & Eggs", "unit": "100g block",
        "image_url": "https://images.unsplash.com/photo-1619984512347-e44dc7d80f7f?w=800",
        "tags": ["parmesan", "cheese", "pasta", "italian", "cooking", "grating"],
        "stock": 60, "lat": 28.6141, "lng": 77.2093,
    },

    # ── General Everyday Products ────────────────────────────────────────────
    {
        "name": "Amul Taza Fresh Milk",
        "description": "Fresh pasteurized toned milk, rich in calcium, protein, and vitamins. Daily essential for breakfast, tea, coffee, and cooking.",
        "price": 1.49, "category": "Dairy & Eggs", "unit": "1L",
        "image_url": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800",
        "tags": ["milk", "dairy", "breakfast", "calcium", "protein"],
        "stock": 100, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Whole Wheat Bread",
        "description": "Freshly baked 100% whole wheat bread loaf. High fibre, low glycemic index. Healthy choice for breakfast sandwiches and diet eating.",
        "price": 3.49, "category": "Bakery", "unit": "loaf",
        "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
        "tags": ["bread", "wheat", "breakfast", "fibre", "healthy"],
        "stock": 60, "lat": 28.6135, "lng": 77.2085,
    },
    {
        "name": "Organic Tomatoes",
        "description": "Red, ripe, juicy organic vine tomatoes. Rich in lycopene and Vitamin C. Great for salads, cooking, and smoothies.",
        "price": 4.99, "category": "Vegetables", "unit": "1kg",
        "image_url": "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800",
        "tags": ["tomato", "vegetable", "salad", "vitamin c", "organic", "cooking"],
        "stock": 80, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Spinach Leaves",
        "description": "Fresh baby spinach rich in iron, folate, calcium, and vitamins. Fights anaemia and weakness. Excellent for salads, smoothies, and cooking.",
        "price": 2.99, "category": "Vegetables", "unit": "250g",
        "image_url": "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800",
        "tags": ["spinach", "iron", "vitamin", "anaemia", "weakness", "salad", "green", "healthy"],
        "stock": 70, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Dark Chocolate 85%",
        "description": "85% cacao dark chocolate. Rich in antioxidants, magnesium, and mood-boosting compounds. Low sugar, keto-friendly, and heart-healthy.",
        "price": 4.49, "category": "Snacks", "unit": "100g bar",
        "image_url": "https://images.unsplash.com/photo-1606312619070-d48b8c7e9d67?w=800",
        "tags": ["dark chocolate", "antioxidant", "keto", "mood", "magnesium", "energy"],
        "stock": 100, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Lemon (Fresh)",
        "description": "Fresh lemons packed with Vitamin C. Natural remedy for cold, sore throat, and digestion. Used in lemon tea, detox water, and cooking.",
        "price": 1.99, "category": "Fruits", "unit": "6 pieces",
        "image_url": "https://images.unsplash.com/photo-1590502593747-42a996133562?w=800",
        "tags": ["lemon", "vitamin c", "cold", "immunity", "detox", "sore throat", "antibacterial"],
        "stock": 150, "lat": 28.6140, "lng": 77.2091,
    },
    {
        "name": "Isabgol (Psyllium Husk)",
        "description": "Natural dietary fibre supplement. Relieves constipation, supports digestion, reduces cholesterol, and helps with weight management.",
        "price": 5.49, "category": "Health", "unit": "200g",
        "image_url": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800",
        "tags": ["fibre", "digestion", "constipation", "weight loss", "gut health", "psyllium"],
        "stock": 80, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Peanut Butter (Natural)",
        "description": "100% natural peanut butter with no added sugar or palm oil. High in protein and healthy fats. Perfect for gym, keto, and healthy snacking.",
        "price": 7.99, "category": "Pantry", "unit": "500g jar",
        "image_url": "https://images.unsplash.com/photo-1519915028121-7d3463d5b1ef?w=800",
        "tags": ["peanut butter", "protein", "keto", "gym", "healthy fat", "snack", "energy"],
        "stock": 100, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Lays Classic Potato Chips",
        "description": "Crispy, thinly sliced classic salted potato chips. America's favourite snack.",
        "price": 1.99, "category": "Snacks", "unit": "1 packet",
        "image_url": "https://images.unsplash.com/photo-1566478989037-e924e5ba03ef?w=800",
        "tags": ["chips", "potato", "salty", "snack"],
        "stock": 200, "lat": 28.6139, "lng": 77.2090,
    },
    {
        "name": "Coca-Cola Zero Sugar",
        "description": "Zero sugar, same great Coca-Cola taste. Refreshing cold drink for any occasion.",
        "price": 2.49, "category": "Beverages", "unit": "2L Bottle",
        "image_url": "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=800",
        "tags": ["soda", "coke", "cold drink", "zero sugar", "beverage"],
        "stock": 120, "lat": 28.6142, "lng": 77.2095,
    },
    {
        "name": "Farm Fresh Apples",
        "description": "Crisp, juicy red apples. Rich in fibre, vitamin C, and antioxidants. An apple a day keeps the doctor away. Great for snacking and immunity.",
        "price": 4.99, "category": "Fruits", "unit": "1kg",
        "image_url": "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=800",
        "tags": ["apple", "fruit", "vitamin c", "fibre", "immunity", "healthy snack"],
        "stock": 90, "lat": 28.6139, "lng": 77.2090,
    },
]


def seed():
    print("🛒 Starting Semantic Search Product Seeding...")

    # Register seller (or login if exists)
    seller_data = {
        "email": "demo_seller@blinkit.com",
        "name": "BlinkIt Demo Store",
        "password": "password123",
        "role": "seller",
        "phone": "9998887776",
    }
    requests.post(f"{BASE_URL}/auth/register", json=seller_data, timeout=10)
    login = requests.post(f"{BASE_URL}/auth/login",
                           json={"email": "demo_seller@blinkit.com", "password": "password123"}, timeout=10)
    if login.status_code != 200:
        print("❌ Login failed:", login.json())
        sys.exit(1)

    token = login.json()["access_token"]
    headers = {"Authorization": f"Bearer {token}"}
    print(f"🔑 Authenticated. Uploading {len(PRODUCTS)} products with AI embeddings...\n")

    ok, fail = 0, 0
    for p in PRODUCTS:
        res = requests.post(f"{BASE_URL}/products", json=p, headers=headers, timeout=60)
        if res.status_code == 201:
            print(f"  ✅ {p['name']}")
            ok += 1
        else:
            detail = res.json().get("detail", res.text)
            print(f"  ❌ {p['name']}: {detail}")
            fail += 1

    print(f"\n🎉 Done! {ok} added, {fail} failed.")


if __name__ == "__main__":
    seed()
